# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
platform :ios do
     desc "Create dev ipa"
     lane :build_beta_dev do
         enable_automatic_code_signing
         increment_build_number
         build_app(scheme: "MPProject")
      end
      desc "Upload dev to Firebase"
      lane :upload_firebase_dev do
         firebase_app_distribution(
            ipa_path: "./fastlane/builds/mpproject.ipa",
            app: "mpproject-dj01"
         )
      end
 end

